# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ECG_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba("
                                 "124, 27, 214, 255), stop:0.505682 rgba(5, 113, 244, 255), stop:0.926136 rgba(55, "
                                 "185, 239, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, -10, 691, 131))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setStyleSheet("font: 12pt \"Montserrat\";\n"
                                 "background: transparent;"
                                 )
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 160, 321, 51))
        self.label_2.setStyleSheet("background: transparent;\n")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 250, 361, 41))
        self.label_3.setStyleSheet("background: transparent;\n")
        self.label_3.setObjectName("label_3")
        self.btn_calc_pulse = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.btn_calc_pulse.setGeometry(QtCore.QRect(510, 450, 231, 51))
        self.btn_calc_pulse.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_calc_pulse.setFont(font)
        self.btn_calc_pulse.setTabletTracking(False)
        self.btn_calc_pulse.setStatusTip("")
        self.btn_calc_pulse.setWhatsThis("")
        self.btn_calc_pulse.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../PycharmProjects/desktop_app/static/icon_pulse.png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        self.btn_calc_pulse.setIcon(icon)
        self.btn_calc_pulse.setIconSize(QtCore.QSize(30, 30))
        self.btn_calc_pulse.setShortcut("")
        self.btn_calc_pulse.setObjectName("btn_calc_pulse")
        self.ecg_removal_rate = QtWidgets.QLineEdit(self.centralwidget)
        self.ecg_removal_rate.setGeometry(QtCore.QRect(430, 250, 181, 41))
        self.ecg_removal_rate.setAcceptDrops(False)
        self.ecg_removal_rate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ecg_removal_rate.setStyleSheet("background: transparent;\n"
                                            "border: 2px solid \'black\';\n"
                                            "border-radius: 10;\n"
                                            "color:black;\n"
                                            "font: 16pt \"Montserrat\";"
                                            )
        self.ecg_removal_rate.setText("")
        self.ecg_removal_rate.setObjectName("ecg_removal_rate")
        self.dist_between_teeth = QtWidgets.QLineEdit(self.centralwidget)
        self.dist_between_teeth.setGeometry(QtCore.QRect(430, 170, 181, 41))
        self.dist_between_teeth.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dist_between_teeth.setStyleSheet("background: transparent;\n"
                                              "border: 2px solid \'black\';\n"
                                              "border-radius: 10;\n"
                                              "color: black;\n"
                                              "font: 16pt \"Montserrat\";"
                                              )
        self.dist_between_teeth.setText("")
        self.dist_between_teeth.setObjectName("dist_between_teeth")
        self.pulse = QtWidgets.QLineEdit(self.centralwidget)
        self.pulse.setGeometry(QtCore.QRect(430, 330, 181, 41))
        self.pulse.setStyleSheet("background: transparent;\n"
                                 "border: 2px solid \'black\';\n"
                                 "border-radius: 10;\n"
                                 "color:black;\n"
                                 "font: 16pt \"Montserrat\";"
                                 )
        self.pulse.setObjectName("pulse")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 310, 251, 51))
        self.label_4.setStyleSheet("background: transparent;\n")
        self.label_4.setObjectName("label_4")
        self.label_2.raise_()
        self.label_3.raise_()
        self.btn_calc_pulse.raise_()
        self.label.raise_()
        self.ecg_removal_rate.raise_()
        self.dist_between_teeth.raise_()
        self.pulse.raise_()
        self.label_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p><span style=\" font-size:24pt;\">Калькулятор пульса по "
                                      "результатам ЭКГ</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:18pt;\">Расстояние между "
                                        "зубцами</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:18pt;\">Скорость снятия "
                                        "кардиограммы</span></p></body></html>"))
        self.btn_calc_pulse.setText(_translate("MainWindow", "Рассчитать пульс"))
        self.ecg_removal_rate.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.ecg_removal_rate.setWhatsThis(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">ygfhgh</p></body></html>"))
        self.dist_between_teeth.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.dist_between_teeth.setWhatsThis(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">ygfhgh</p></body></html>"))
        self.label_4.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" "
                                        "font-size:18pt;\">Пульс</span></p></body></html>"))
