# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ecg_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1048, 639)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        MainWindow.setStyleSheet(
            "background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(124, 27, 214, 255), "
            "stop:0.505682 rgba(5, 113, 244, 255), stop:0.926136 rgba(55, 185, 239, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.pulse = QtWidgets.QLineEdit(self.centralwidget)
        self.pulse.setGeometry(QtCore.QRect(10, 530, 321, 41))
        self.pulse.setStyleSheet("background: transparent;\n"
                                 "border: 2px solid \'black\';\n"
                                 "border-radius: 10;\n"
                                 "color:black;\n"
                                 "font: 16pt \"Montserrat\";")
        self.pulse.setObjectName("pulse")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(10, 490, 1031, 31))
        self.label_4.setMaximumSize(QtCore.QSize(2444354, 45545))
        self.label_4.setStyleSheet("background: transparent;\n"
                                   "")
        self.label_4.setObjectName("label_4")
        self.btn_calc_pulse = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.btn_calc_pulse.setGeometry(QtCore.QRect(10, 430, 1031, 61))
        self.btn_calc_pulse.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_calc_pulse.setFont(font)
        self.btn_calc_pulse.setTabletTracking(False)
        self.btn_calc_pulse.setStatusTip("")
        self.btn_calc_pulse.setWhatsThis("")
        self.btn_calc_pulse.setAutoFillBackground(False)
        self.btn_calc_pulse.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../PycharmProjects/desktop_app/static/icon_pulse.png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        self.btn_calc_pulse.setIcon(icon)
        self.btn_calc_pulse.setIconSize(QtCore.QSize(30, 30))
        self.btn_calc_pulse.setShortcut("")
        self.btn_calc_pulse.setObjectName("btn_calc_pulse")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setEnabled(True)
        self.graphicsView.setGeometry(QtCore.QRect(9, 98, 1031, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(760, 0))
        self.graphicsView.setMouseTracking(True)
        self.graphicsView.setStyleSheet("background:\'white\';")
        self.graphicsView.setInteractive(True)
        self.graphicsView.setObjectName("graphicsView")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1031, 81))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setStyleSheet("font: 12pt \"Montserrat\";\n"
                                 "background: transparent;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.info_from_database = QtWidgets.QTextEdit(self.widget)
        self.info_from_database.setStyleSheet("font: 12pt \"Montserrat\";\n"
                                    "background: transparent;")
        self.info_from_database.setObjectName("textEdit")
        self.gridLayout.addWidget(self.info_from_database, 0, 1, 1, 1)
        self.btn_calc_pulse.raise_()
        self.pulse.raise_()
        self.label_4.raise_()
        self.graphicsView.raise_()
        self.label.raise_()
        self.info_from_database.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1048, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:18pt;\">Ваш пульс</span></p></body></html>"))
        self.btn_calc_pulse.setText(_translate("MainWindow", "Рассчитать пульс"))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p><span style=\" font-size:24pt;\">Калькулятор пульса по результатам ЭКГ</span></p></body></html>"))


from pyqtgraph import PlotWidget
